# Generated by Django 5.2.7 on 2025-10-23 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_entries_delete_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
